version: "3.7"
volumes:
  prometheus_data: {}
  grafana_data: {}
networks:
  slislo:
services:
  goapp:
    build: ./goapp
    networks:
      - slislo
    ports:
      - 2112:2112
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - slislo
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    restart: always
    depends_on:
      - goapp
  alertmanager:
    image: prom/alertmanager
    networks:
      - slislo
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yaml"
      - "--storage.path=/alertmanager"
  grafana:
    image: grafana/grafana
    user: "472"
    networks:
      - slislo
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/
    env_file:
      - ./grafana/config
    restart: always
