global:
  scrape_interval:     10s
  evaluation_interval: 10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'slislo'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'rules.yaml'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
- job_name: slislo
  scrape_interval: 1s
  static_configs:
    - targets: ['goapp:2112']
