groups:
- name: slislo
  rules:
  - alert: GoappErroring
    expr: sum(rate(requests{code!="200"}[10m])) > 0.1
    for: 1m
    annotations:
      title: 'Instance {{ $labels.instance }} is erroring'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has thrown errors'
    labels:
      severity: 'critical'
