groups:
- name: slislo
  rules:
  - alert: GoappErroring
<<<<<<< HEAD
    expr: sum(rate(requests{code="500"}[1m])) > 0.1
=======
    expr: sum(rate(requests{code!="200"}[10m])) > 0.1
>>>>>>> 52d091c82d447a2558ff1dc342f7f083b961978d
    for: 1m
    annotations:
      title: '{{ $labels.job }} is erroring'
      description: 'Our program {{ $labels.job }} has an error rate of greater than 10%.  You can see the RED metrics for this chart at the following URL: http://localhost:3000/d/o0_KG03Zz/red-metrics-dashboard?orgId=1'
    labels:
      severity: 'critical'
