groups:
- name: slislo
  rules:
  - alert: GoappErroring
    expr: go_sli_slo_app_requests_total{code="500"} > 0
    #for: 10s
    annotations:
      title: 'Instance {{ $labels.instance }} is erroring'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has thrown errors'
    labels:
      severity: 'critical'
