{
 "title": "RED Metrics Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (Requests / Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(requests[1m]))", "legendFormat": "Rate of {{code}} Status Code" }
   ]
  },
  {
   "title": "Error Rate (Requests / Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests {code=\"500\"}[1m])) \n/ \nsum(rate(requests[1m]))",
     "legendFormat": "Ratio of Error Responses"
    }
   ]
  },
  {
   "title": "Duration Latency Buckets (Requests / Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(duration_bucket[1m])) by (le))",
     "legendFormat": "50th Percentile Duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(duration_bucket[1m])) by (le))",
     "legendFormat": "95th Percentile Duration"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(duration_bucket[1m])) by (le))",
     "legendFormat": "99th Percentile Duration"
    }
   ]
  }
 ]
}